// <auto-generated>
//     Generated from protocol/catalog/commands.json and protocol/VERSION by
//     protocol/scripts/generate-csharp-catalog.mjs. DO NOT EDIT BY HAND.
//     Regenerate: node protocol/scripts/generate-csharp-catalog.mjs
//     Verified up-to-date in CI by protocol/scripts/check-drift.mjs.
// </auto-generated>
namespace UnityEditorMCP.Core
{
    /// <summary>The command surface declared by the protocol catalog.</summary>
    public static class CommandCatalog
    {
        /// <summary>Protocol contract version (protocol/VERSION).</summary>
        public const string ProtocolVersion = "1.0.0";

        /// <summary>Every command whose catalog "sides" includes "editor".</summary>
        public static readonly string[] EditorCommands =
        {
            "add_component",
            "analyze_asset_dependencies",
            "analyze_scene_contents",
            "analyze_screenshot",
            "cancel_tests",
            "capture_screenshot",
            "clear_console",
            "clear_logs",
            "click_ui_element",
            "create_gameobject",
            "create_material",
            "create_prefab",
            "create_scene",
            "create_script",
            "delete_gameobject",
            "delete_script",
            "enhanced_read_logs",
            "execute_menu_item",
            "exit_prefab_mode",
            "find_by_component",
            "find_gameobject",
            "find_ui_elements",
            "get_compilation_state",
            "get_component_types",
            "get_component_values",
            "get_editor_state",
            "get_gameobject_details",
            "get_hierarchy",
            "get_object_references",
            "get_scene_info",
            "get_test_results",
            "get_ui_element_state",
            "handshake",
            "instantiate_prefab",
            "list_components",
            "list_scenes",
            "list_scripts",
            "list_tests",
            "load_scene",
            "manage_asset_database",
            "manage_asset_import_settings",
            "manage_layers",
            "manage_selection",
            "manage_tags",
            "manage_tools",
            "manage_windows",
            "modify_component",
            "modify_gameobject",
            "modify_material",
            "modify_prefab",
            "open_prefab",
            "pause_game",
            "ping",
            "play_game",
            "read_logs",
            "read_script",
            "refresh_assets",
            "remove_component",
            "run_tests",
            "save_prefab",
            "save_scene",
            "set_ui_element_value",
            "simulate_ui_input",
            "start_compilation_monitoring",
            "stop_compilation_monitoring",
            "stop_game",
            "update_script",
            "validate_script",
        };

        /// <summary>Declared-but-unimplemented editor commands (catalog knownGaps).</summary>
        public static readonly string[] KnownEditorGaps =
        {

        };
    }
}
